// TODO: connect to API once endpoint returns real data — remove this file
import type { ReservationEntry } from './types';

const today = new Date();
function h(hour: number, min = 0): string {
  return new Date(today.getFullYear(), today.getMonth(), today.getDate(), hour, min).toISOString();
}

export const MOCK_RESERVATIONS: ReservationEntry[] = [
  {
    id: 'mock-r1',
    user_id: 'a1b2c3d4-aaaa-bbbb-cccc-111111111111',
    entry_type: 'reservation',
    time_slot_id: 'slot-1',
    station_id: 'station-1',
    vehicle_format_id: 'fmt-1',
    status: 'confirmed',
    queue_position: null,
    amount_paid: '35.00',
    created_at: h(9, 0),
    updated_at: h(9, 0),
    completed_at: null,
  },
  {
    id: 'mock-r2',
    user_id: 'b2c3d4e5-aaaa-bbbb-cccc-222222222222',
    entry_type: 'reservation',
    time_slot_id: 'slot-2',
    station_id: 'station-1',
    vehicle_format_id: 'fmt-2',
    status: 'in_progress',
    queue_position: null,
    amount_paid: '45.00',
    created_at: h(9, 30),
    updated_at: h(9, 35),
    completed_at: null,
  },
  {
    id: 'mock-r3',
    user_id: 'c3d4e5f6-aaaa-bbbb-cccc-333333333333',
    entry_type: 'queue',
    time_slot_id: null,
    station_id: 'station-1',
    vehicle_format_id: 'fmt-1',
    status: 'pending',
    queue_position: 1,
    amount_paid: '25.00',
    created_at: h(10, 0),
    updated_at: h(10, 0),
    completed_at: null,
  },
  {
    id: 'mock-r4',
    user_id: 'd4e5f6a7-aaaa-bbbb-cccc-444444444444',
    entry_type: 'reservation',
    time_slot_id: 'slot-3',
    station_id: 'station-1',
    vehicle_format_id: 'fmt-2',
    status: 'completed',
    queue_position: null,
    amount_paid: '55.00',
    created_at: h(8, 0),
    updated_at: h(8, 45),
    completed_at: h(8, 45),
  },
  {
    id: 'mock-r5',
    user_id: 'e5f6a7b8-aaaa-bbbb-cccc-555555555555',
    entry_type: 'reservation',
    time_slot_id: 'slot-4',
    station_id: 'station-1',
    vehicle_format_id: 'fmt-1',
    status: 'cancelled',
    queue_position: null,
    amount_paid: '30.00',
    created_at: h(7, 30),
    updated_at: h(7, 45),
    completed_at: null,
  },
  {
    id: 'mock-r6',
    user_id: 'f6a7b8c9-aaaa-bbbb-cccc-666666666666',
    entry_type: 'reservation',
    time_slot_id: 'slot-5',
    station_id: 'station-1',
    vehicle_format_id: 'fmt-2',
    status: 'late',
    queue_position: null,
    amount_paid: '40.00',
    created_at: h(10, 30),
    updated_at: h(11, 0),
    completed_at: null,
  },
  {
    id: 'mock-r7',
    user_id: 'a7b8c9d0-aaaa-bbbb-cccc-777777777777',
    entry_type: 'queue',
    time_slot_id: null,
    station_id: 'station-1',
    vehicle_format_id: 'fmt-1',
    status: 'pending',
    queue_position: 2,
    amount_paid: '28.00',
    created_at: h(10, 15),
    updated_at: h(10, 15),
    completed_at: null,
  },
  {
    id: 'mock-r8',
    user_id: 'b8c9d0e1-aaaa-bbbb-cccc-888888888888',
    entry_type: 'reservation',
    time_slot_id: 'slot-6',
    station_id: 'station-1',
    vehicle_format_id: 'fmt-2',
    status: 'confirmed',
    queue_position: null,
    amount_paid: '50.00',
    created_at: h(11, 0),
    updated_at: h(11, 0),
    completed_at: null,
  },
];
