/**
 * API error codes (shared server and client).
 * Used in error response body as `code`; status code remains the contract (2xx success, 4xx/5xx error).
 */
export enum ApiCode {
  // Core validation and auth
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // Auth-related
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',
  BUSINESS_NOT_APPROVED = 'BUSINESS_NOT_APPROVED',
  BUSINESS_REJECTED = 'BUSINESS_REJECTED',
  WRONG_LOGIN_SPACE = 'WRONG_LOGIN_SPACE',
  EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED',

  // Server errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Reservations
  SLOT_FULL = 'SLOT_FULL',
  ACTIVE_RESERVATION_EXISTS = 'ACTIVE_RESERVATION_EXISTS',

  // Ratings
  ALREADY_RATED = 'ALREADY_RATED',
  RATING_WINDOW_EXPIRED = 'RATING_WINDOW_EXPIRED',
  RESERVATION_NOT_COMPLETED = 'RESERVATION_NOT_COMPLETED',

  // Tips
  TIP_ALREADY_EXISTS = 'TIP_ALREADY_EXISTS',

  // Station
  STATION_CLOSED = 'STATION_CLOSED',

  // Disputes
  DISPUTE_ALREADY_EXISTS = 'DISPUTE_ALREADY_EXISTS',
  DISPUTE_ALREADY_CLOSED = 'DISPUTE_ALREADY_CLOSED',
  REFUND_NOT_ELIGIBLE = 'REFUND_NOT_ELIGIBLE',
}
